// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DynamicClassroomsController from "./dynamic_classrooms_controller"
application.register("dynamic-classrooms", DynamicClassroomsController)

import NestedRondoController from "./nested_rondo_controller"
application.register("nested-rondo", NestedRondoController)

import SearchController from "./search_controller"
application.register("search", SearchController)
